import {ING,RECIPES,FORECAST,ROUTES,CUSTOMERS} from './data.js';
import {restaurantScene} from './diner.js';
import {PHASES,newGame,save,load,today,enterField,collectNode,settleField,skipField,purchase,startCook,moveTile,beat,finishCook,synergyFor,canMenu,prepDish,createService,tick,expedite,markManual,closeService,nextPhase,advanceDay,buyUpgrade,canUse,setServicePaused,resumeBreak,breakPrep,setFlame,tossWok,previewHeat} from './engine.js';
let game=load()||newGame();let message='欢迎来到怪味食堂！先观察今晚的客人。';let tileSelected=null;let dragFrom=null;let selectedOrderId=null;let selectedStation=null;const app=document.querySelector('#app');
const clean=s=>String(s).replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;').replaceAll('"','&quot;');
const btn=(action,label,disabled=false,cls='')=>`<button class="button ${cls}" data-act="${action}" ${disabled?'disabled':''}>${label}</button>`;
const ingredients=()=>Object.entries(ING).map(([id,ing])=>`<span class="stock">${ing.emoji} ${ing.name} <b>×${game.inventory[id]||0}</b></span>`).join('');
function header(){const phase={forecast:'今日情报',field:'野外取材',research:'研发料理',menu:'三菜构筑',prep:'备餐选择',service:'营业中',report:'今晚日报',upgrade:'成长与新日'}[game.phase];return `<header><div><div class="eyebrow">ODDPOT KITCHEN · 经营场景原型</div><h1>🍳 怪味食堂 <span class="subver">v0.2 · 场景版</span></h1></div><div class="daybadge">第 ${game.cycle} 轮<br><strong>DAY ${game.day}</strong></div></header><div class="stats"><span>🪙 ${game.coins} 金币</span><span>⭐ ${game.reputation} 声望</span><span>📖 ${Object.keys(game.recipes).length}/5 道菜</span></div><nav class="steps">${['情报','取材','研发','菜单','备餐','营业','日报','升级'].map((n,i)=>`<span class="${PHASES[i]===game.phase?'current':''} ${i<PHASES.indexOf(game.phase)?'completed':''}">${n}</span>`).join('')}</nav><p class="toast" role="status">${clean(message)}</p>${game.phase==='service'?'<div class="compact-stocks">🎒 仓库可在营业日报后查看 · 顾客点菜将实际消耗食材</div>':`<section class="panel inventory"><div class="paneltop"><h2>🍱 食材仓库</h2><small>真实库存 · 跨日保留</small></div><div class="stockrow">${ingredients()}</div></section>`}<div class="phaseheading"><h2>${phase}</h2><small>${today(game).name}</small></div>`}
function forecast(){const t=today(game);const guide=game.day===1?'建议尝试蘑菇焖鸡 + 菌香小炒，形成「菌香组合」。':game.day===2?'冒险者喜欢辣味。去取火椒，研发辣椒炒肉，再调整菜单。':'今晚踢馆！上架辣椒炒肉，与蘑菇焖鸡形成「辛香暖胃」，评委看品质与出餐。';return `<section class="panel feature"><div class="eyebrow">TODAY'S FORECAST</div><h2>${t.name}</h2><p>${t.hint}</p><div class="tip">💡 ${guide}</div>${game.day===3?'<div class="dangerhint">🔥 爆炎厨王：辛香与猛火 / 对手 70 分 / 最后一单为评委单。首胜解锁「猛火掌控」。</div>':''}${btn('to-field','查看食材路线 →',false,'primary')}</section>${restaurantScene(game,{interactive:false,compact:true})}`}
function field(){let f=game.field;return `<section class="panel"><p>缺什么，就找什么。采集所得会直接进入餐馆仓库（每个游戏日最多一次）。</p>${!f?`<h3>① 指定目标食材</h3><div class="choices">${Object.entries(ING).map(([id,ing])=>`<button data-target="${id}" class="chip ${game.selectedTarget===id?'selected':''}">${ing.emoji} ${ing.name}</button>`).join('')}</div><h3>② 选择路线</h3><div class="routegrid">${ROUTES.map(x=>`<button class="route" data-route="${x.id}"><strong>${x.emoji} ${x.name}</strong><small>${x.subtitle}</small><span>目标保底：${ING[game.selectedTarget].name} ×2</span></button>`).join('')}</div>${btn('skip-field','库存足够，跳过探索 →')}`:`<div class="fieldhead"><strong>${f.route==='safe'?'🌿 安全采集线':'🦬 野牛狩猎线'}</strong><span>❤️ ${'♥'.repeat(f.hp)} · 🎒 ${Object.keys(f.bag).length}/6 格</span></div><div class="bag">${Object.entries(f.bag).length?Object.entries(f.bag).map(([id,n])=>`${ING[id].emoji} ${ING[id].name} ×${n}`).join('　'):'背包为空'}</div>${f.node<f.sequence.length&&!f.finished?`<div class="node"><div class="eyebrow">节点 ${f.node+1}/3</div><h2>${f.sequence[f.node].type==='danger'?'⚠️':f.sequence[f.node].type==='event'?'✨':'🌱'} ${f.sequence[f.node].label}</h2><p>可获得 ${ING[f.sequence[f.node].id].name} ×${f.sequence[f.node].n} ${f.sequence[f.node].type==='danger'?'· 有损伤风险':''}</p>${btn('collect','采集 / 应对 →',false,'primary')}${btn('skip-node','绕过此节点')}</div>`:`<div class="tip">探索节点已完成，可以结算背包。</div>`}${btn('retreat','带上已采集食材回店 →',false,'strong')}`}</section>`}
const cookNames=Object.entries(RECIPES);
const choicesCook=()=>`<section class="panel"><h3>从已知配方开始</h3><div class="recipes">${cookNames.filter(([id,r])=>!r.hidden||game.recipes[id]).map(([id,r])=>`<div class="reciperow"><span class="recipeicon">${r.emoji}</span><div class="recipedesc"><b>${r.name}${game.recipes[id]?' · 已会':' · 待研发'}</b><small>${r.ids.map(x=>ING[x].emoji).join(' + ')} · ${r.method==='stir'?'爆炒':'焖煮'} ${r.station} · ${r.time}s</small></div>${btn(`try:${id}`,'下锅',!canUse(game,r.ids))}</div>`).join('')}</div><h3>自由实验 · 寻找隐藏变体</h3><div class="tip">🔥 线索：让火椒与肉相邻至少两拍，再让蒜瓣在中心旺火爆香。</div><div class="freecook">${[0,1,2].map((i)=>`<select aria-label="自选食材${i+1}" data-exp-ing="${i}"><option value="">${i===2?'（可选）第三食材':'选择食材'}</option>${Object.entries(ING).map(([id,ing])=>`<option value="${id}" ${(i===0&&id==='chicken'||i===1&&id==='mushroom')?'selected':''}>${ing.emoji} ${ing.name}</option>`).join('')}</select>`).join('')}<select aria-label="选择技法" id="exp-method"><option value="stir">🔥 爆炒</option><option value="stew">🍲 焖煮</option></select></div>${btn('free-cook','🧪 自由下锅尝试',false,'strong')}<p class="hint">重复食材或库存不足时无法开始实验，实验失败仍真实耗材。</p>${btn('to-menu','暂时不做，去搭配菜单 →',false,'primary')}</section><section class="panel"><h3>快速采购（防止缺料卡住）</h3><div class="choices">${['chicken','chili','garlic','mushroom','cabbage'].map(id=>`<button class="chip" data-buy="${id}">+1 ${ING[id].emoji} <small>🪙${ING[id].cost}</small></button>`).join('')}</div></section>`;
function cookPanel(){const c=game.cook;if(!c)return '';const temp=c.method==='stir'?[1,2,1,2,3,2,1,2,1]:[1,1,1,1,2,1,1,1,1];const tiles=c.tiles.map((t,i)=>`<button class="tile ${t?'filled':''} ${tileSelected===i?'active':''}" data-tile="${i}"><span class="heatnote">+${temp[i]}🔥</span>${t?`<span class="foodicon">${ING[t.id].emoji}</span><small>${ING[t.id].name}</small><b>热量 ${t.heat}</b>`:'<span class="emptytile">＋</span>'}</button>`).join('');return `<section class="panel cookpanel"><div class="paneltop"><h2>🍳 ${c.method==='stir'?'爆炒':'焖煮'}构筑盘</h2><span class="badge">${c.beats}/3 拍</span></div><p class="hint">拖动食材换位，也能试试颠锅。先看受热预测，再选择小火 / 标准 / 旺火。</p><div class="wok"><div class="board">${tiles}</div></div><div class="flame-selector"><div class="paneltop"><b>🔥 本拍火力</b><span>${c.flame===1?'旺火 · 更易焦':c.flame===-1?'小火 · 更温和':'标准火候'}</span></div><div class="flame-buttons">${[[-1,'🫕 小火'],[0,'🔥 标准'],[1,'♨️ 旺火']].map(([n,label])=>btn(`flame:${n}`,label,false,`tiny ${c.flame===n?'flame-active':''}`)).join('')}</div><div class="predict-heat">下拍预判：${c.tiles.map((t,i)=>t?`<span class="${previewHeat(c)[i]>ING[t.id].hi?'risk':previewHeat(c)[i]>=ING[t.id].lo?'good':''}">${ING[t.id].emoji} ${previewHeat(c)[i]} / ${ING[t.id].lo}–${ING[t.id].hi}</span>`:'').join('')}</div>${btn('toss','↪️ 颠锅：外圈食材顺时针翻转',c.beats>0&&c.movedThisBeat,'strong')}</div><div class="heatguide">${c.tiles.filter(Boolean).map(t=>`<span class="${t.heat>ING[t.id].hi?'over':t.heat>=ING[t.id].lo?'ripe':''}">${ING[t.id].emoji} ${t.heat} / ${ING[t.id].lo}–${ING[t.id].hi}</span>`).join('')}</div><div class="beats">${[1,2,3].map(n=>`<span class="${c.beats>=n?'on':''}">${c.beats>=n?'●':'○'}</span>`).join('')}</div>${c.beats<3?btn('heat','🔥 确认加热这一拍',false,'primary'):btn('finish-cook','✨ 出锅并评价',false,'primary')}<p class="hint">${[...new Set(c.effects)].join(' · ')||'试试让火椒与肉相邻两拍，或让蒜瓣在中心爆香。'}</p></section>`}
function cookResult(){const r=game.lastCook;if(!r)return '';return `<section class="panel result"><h3>${r.sellable?'🎉 成功研发！':'🧪 这锅未达标'}</h3><div class="bigscore">${r.quality}<small>/100 品质</small></div><h3>${r.recipeId?RECIPES[r.recipeId].name:'未知组合'}</h3><p>${r.reason} ${r.effects.join(' · ')}</p><div class="heatguide">${r.heat.map(t=>`<span>${ING[t.id].emoji} ${t.heat}/${t.ideal}</span>`).join('')}</div></section>`}
function research(){return `${game.cook?cookPanel():`${cookResult()}${choicesCook()}`}`}
function menu(){let sy=synergyFor(game.menu);const count={};game.menu.forEach(id=>{const st=RECIPES[id]?.station;if(st)count[st]=(count[st]||0)+1});const ids=Object.keys(game.recipes);return `<section class="panel"><p>从已研发料理中选择 3 道。比较风味覆盖、厨具占用与套餐共鸣。</p>${[0,1,2].map(i=>`<div class="slot"><span>菜单 ${i+1}</span><select data-slot="${i}">${ids.map(id=>`<option value="${id}" ${game.menu[i]===id?'selected':''}>${RECIPES[id].emoji} ${RECIPES[id].name} · ${RECIPES[id].station}</option>`).join('')}</select></div>`).join('')}<div class="synergy"><strong>${sy?'✨ 已激活 '+sy:'暂无主共鸣'}</strong><p>${sy==='辛香暖胃'?'冒险者对辣味菜的适配增加。':sy==='菌香组合'?'家庭与评论家的菌香适配增加。':'尝试辣味肉菜 + 炖煮菜，或两道不同菌香菜。'}</p></div><div class="kitchenpreview"><div>🍳 WOK 炒锅<br><b>${count.WOK||0} 道菜争抢</b></div><div>🍲 POT 炖锅<br><b>${count.POT||0} 道菜争抢</b></div></div>${btn('to-prep','确认今晚菜单 →',!canMenu(game),'primary')}</section>${restaurantScene(game,{interactive:false,compact:true})}<section class="panel"><h3>成本 / 产能参考</h3>${game.menu.map(id=>RECIPES[id]?`<div class="economyline">${RECIPES[id].emoji} ${RECIPES[id].name}<span>🪙${RECIPES[id].price} · ${RECIPES[id].time}s · ${RECIPES[id].station}</span></div>`:'').join('')}</section>`}
function prep(){return `<section class="panel"><p>可提前制作少量菜。备餐立即消耗真实食材，省去营业时的排队；未卖完会报损。</p><div class="tip">${game.day===3?'🔥 挑战营业：评委喜欢辣味和爆香。':''}本晚共三波、约 7 单、两张餐桌、WOK/POT 各一台。</div>${game.menu.map(id=>{const r=RECIPES[id];return `<div class="reciperow"><span class="recipeicon">${r.emoji}</span><div class="recipedesc"><b>${r.name}</b><small>已备 ${game.prep[id]||0} 份 · ${r.station} ${r.time}s</small></div>${btn(`prep:${id}`,'+1份',!canUse(game,r.ids))}</div>`}).join('')}${btn('open','🛎️ 进入食堂营业场景',false,'primary')}</section>`}
function service(){
 if(game.cook)return `<section class="panel cooking-in-service"><div class="tip">⏸ 餐厅暂停：你正在亲手制作关键订单。提交后仍要占用正常的工位时间，顾客也会继续等待。</div>${cookPanel()}</section>`;
 const v=game.service;if(!v)return '';
 const served=v.orders.filter(o=>o.status==='served').length;
 const queued=v.orders.filter(o=>o.status==='queued');
 const cooking=v.orders.filter(o=>o.status==='cooking');
 const outside=v.orders.filter(o=>o.status==='waiting').length;
 const selected=v.orders.find(o=>o.id===selectedOrderId);
 const alive=selected&&['queued','cooking'].includes(selected.status);
 const selectedStationOrders=selectedStation?v.orders.filter(o=>RECIPES[o.recipeId]?.station===selectedStation&&['queued','cooking'].includes(o.status)):[];
 const progress=Math.min(100,Math.round(v.time/85*100));
 const waveLabels=['入座','高峰','压轴'];
 const mode=v.done?'结束':v.breakAt?'波次间休整':v.paused?'暂停中':'营业中';
 const latest=v.events.slice(-3).reverse().map(e=>{
  const o=v.orders.find(x=>x.id===e.order),r=RECIPES[e.recipeId||o?.recipeId];
  const desc={arrived:`${CUSTOMERS[o?.segment]?.name||'顾客'}在 ${Number(e.table)+1} 号桌点单`,started:`${r?.name||'料理'}正在下锅`,served:`${r?.name||'料理'}已送达 · 评价 ${e.sat}`,left:'有顾客等太久离店',rejected:e.reason||'拒单',wave_break:'进入波次间休整',emergency_prep:`应急备餐 ${r?.name||''}`,wave_resumed:'下一波开始',failed_cook:'手工菜火候不合格'}[e.type]||'厨房状态已更新';
  return `<span>${desc}</span>`;
 }).join('');
 const selectedHTML=selected?`<div class="inspector">
   <div class="paneltop"><strong>${selected.tableId!=null?`🍽 ${selected.tableId+1} 号桌 · `:''}${CUSTOMERS[selected.segment]?.name||'顾客'}</strong><span class="inspector-state">${{queued:'等待下锅',cooking:'正在烹饪',served:'已出餐',left:'已经离店',rejected:'无法接单'}[selected.status]||'尚未到店'}</span></div>
   <div class="inspector-dish">${RECIPES[selected.recipeId]?.emoji||'🍽'} ${RECIPES[selected.recipeId]?.name||'暂无'} <span>· 匹配 ${selected.fit}</span></div>
   ${alive?`<div class="patience"><span style="width:${Math.max(0,Math.round((1-(v.time-selected.arrival)/selected.patience)*100))}%"></span></div>`:''}
   <div class="inspector-actions">${btn(`prior:${selected.id}`,'⬆️ 插队优先',selected.status!=='queued','strong')}${btn(`manual:${selected.id}`,'🍳 主厨亲做',selected.status!=='queued'||v.manualUsed>=2||!!selected.manual,'strong')}</div>
  </div>`:'';
 return `<section class="panel service-panel">
  <div class="servicehead"><div><strong>${game.day===3?'🔥 爆炎厨王挑战':'🛎️ 今晚开店'} · ${mode}</strong><small>模拟 ${v.time}s · 服务 ${served}/${v.orders.length} · 门外 ${outside} 位待入场</small></div><span class="badge">🪙 +${v.income}</span></div>
  <div class="wave-track">${waveLabels.map((label,i)=>`<span class="${i===v.wave?'current':''} ${i<v.wave?'passed':''}">${i+1}. ${label}</span>`).join('')}</div>
  ${restaurantScene(game,{selectedOrderId,interactive:!v.done})}
  <div class="scene-status"><span>${cooking.length?'🔥 后厨忙碌':'🫖 后厨可用'} · ${queued.length} 单待制作</span><span>⏱ ${progress}%</span></div>
  ${v.breakAt?`<div class="intermission"><div class="eyebrow">WAVE BREAK · 自由思考不计时</div><h3>第 ${v.breakAt} 波结束 · 店长决策</h3><p>可以应急预制一道餐点（仅此一次），减少下一波等待；这份餐点会真实扣原料，卖不完也会报损。</p><div class="intermission-choices">${game.menu.map(id=>btn(`breakprep:${id}`,`+1 ${RECIPES[id].emoji} ${RECIPES[id].name}`,v.breakUsed||!canUse(game,RECIPES[id].ids),'tiny')).join('')}</div>${btn('resume-break','▶️ 迎接下一波',false,'primary')}</div>`:
  v.done?`<div class="tip">今晚所有订单已经结束。看看哪种菜单真正带来了好评价、哪里出现了排队。</div>${btn('close','📊 查看今晚日报 →',false,'primary')}`:
  `<div class="service-controls">${btn('service-toggle',v.paused?'▶️ 开始 / 继续迎客':'⏸ 暂停营业',false,v.paused?'primary':'strong')}<small>点击客人所在餐桌，或点击炒锅与炖锅，直接处理排队。</small></div>`}
  ${selectedHTML||(!selectedStation?`<div class="service-hint">👆 点餐桌查看顾客需求，选择「插队优先」或「主厨亲做」。操作会影响真实的等待和评价。</div>`:'')}
  ${selectedStation?`<div class="inspector"><div class="paneltop"><b>${selectedStation==='WOK'?'🍳 炒锅':'🍲 炖锅'} · 工位任务</b>${btn('clear-selection','收起',false,'tiny')}</div>${selectedStationOrders.length?selectedStationOrders.map(o=>`<button type="button" class="station-queue-item" data-select-order="${o.id}">${RECIPES[o.recipeId]?.emoji||'🍽'} ${RECIPES[o.recipeId]?.name||''} · ${o.status==='cooking'?'制作中':'排队'} ${o.tableId!=null?`· ${o.tableId+1}桌`:''}</button>`).join(''):'<p>现在没有等待这一工位的订单。</p>'}</div>`:''}
  <div class="order-feed"><div class="paneltop"><b>🧾 实时客单</b><small>点单查看优先级和手做机会</small></div>${v.orders.filter(o=>o.status!=='waiting').map(o=>`<button type="button" class="order-feed-item ${o.status} ${o.id===selectedOrderId?'highlight':''}" data-select-order="${o.id}"><span>${CUSTOMERS[o.segment]?.emoji||'🙂'} ${RECIPES[o.recipeId]?.name||'无法点菜'}</span><small>${o.tableId!=null?`${o.tableId+1}桌 · `:''}${{queued:'候餐',cooking:'烹饪中',served:'✓ 已送达',left:'✕ 离店',rejected:'✕ 无法接单'}[o.status]||''}</small></button>`).join('')}</div>
  <div class="event-feed"><b>📣 店内动态</b>${latest||'<span>准备开门，第一位顾客已在餐桌等待。</span>'}</div>
 </section>`;
}
function report(){const r=game.report;if(!r)return '';return `<section class="panel report"><div class="eyebrow">NIGHT REPORT · DAY ${r.day}</div><div class="metrics"><div><small>销售收入</small><strong>🪙 ${r.revenue}</strong></div><div><small>原料耗用估值</small><strong>${r.cost}</strong></div><div><small>经营贡献利润</small><strong>${r.profit}</strong></div><div><small>顾客满意度</small><strong>${r.sat}</strong></div><div><small>成功交付</small><strong>${r.served}/7</strong></div><div><small>离店 / 拒单</small><strong>${r.left} / ${r.rejected}</strong></div></div><div class="tip">💡 ${r.suggested}</div><h3>📊 菜品销量</h3>${Object.entries(r.byDish).map(([id,d])=>`<div class="economyline">${RECIPES[id].name}<span>${d.count} 份 · 评价 ${Math.round(d.totalSat/d.count)}</span></div>`).join('')||'<p>本晚没有售出菜品。</p>'}<p class="hint">锅具忙碌：WOK ${r.congestion.WOK}s / POT ${r.congestion.POT}s；主共鸣：${r.synergy||'无'}。</p>${r.challenge?`<div class="challenge"><h2>${r.won?'🏆 击败爆炎厨王！':'🔥 厨王挑战未通过'}</h2><div class="bigscore">${r.challenge.score}<small> / 70 目标</small></div><div class="metrics fours">${[['顾客体验',r.challenge.service],['主题掌握',r.challenge.theme],['履约率',r.challenge.fulfillment],['评委料理',r.challenge.signature]].map(([n,v])=>`<div><small>${n}</small><strong>${v}</strong></div>`).join('')}</div><p>${r.won?'永久解锁「猛火掌控」：爆炒时可修正一次过火热量。':'失败不清空仓库与收益，下轮第三天可以重试。'}</p></div>`:''}${btn('to-upgrade','结束本日，查看成长 →',false,'primary')}</section>`}
function upgrade(){return `<section class="panel"><h2>🍽️ 食堂持续成长</h2><p>永久保留菜谱、金币、原材料与厨王技法。完成三天后开启新一轮经营主题。</p><div class="tip">${game.tech?'🔥 猛火掌控已解锁：每锅爆炒可对一份过火食材修正 -1 热量。':'🔒 猛火掌控：首次战胜爆炎厨王后获得。'}</div><div class="reciperow"><span class="recipeicon">⚙️</span><div class="recipedesc"><b>炒锅节能改装</b><small>永久升级 · WOK 制作时间 -2 秒（60 金币）</small></div>${btn('upgrade','升级',game.upgrade||game.coins<60)}</div>${btn('next-day',game.day===3?'🔁 进入新一轮 →':'🌅 开始下一天 →',false,'primary')}</section>`}
function render(){app.innerHTML=header()+({forecast,field,research,menu,prep,service,report,upgrade}[game.phase])()+`<footer>🏠 经营场景 v0.2 · 像素占位 / 真实库存与订单结算 <button class="reset" data-act="reset">重置试玩</button></footer>`;save(game)}
function notify(msg){message=msg;render()}
function action(act){if(act==='reset'){if(!confirm('确定清空本机原型存档，从第一天重开？'))return;game=newGame();tileSelected=null;notify('测试存档已重置。');return}
if(act==='free-cook'){const ids=[...app.querySelectorAll('[data-exp-ing]')].map(e=>e.value).filter(Boolean);const method=app.querySelector('#exp-method').value;if(new Set(ids).size!==ids.length){notify('不能在同一锅加入两次相同食材。');return}notify(startCook(game,ids,method)?'自由实验已开始，试试不同温区与联动条件。':'请选择两至三种有库存的食材。');return}
if(act.startsWith('try:')){const id=act.slice(4),r=RECIPES[id];if(startCook(game,r.ids,r.method))notify(`已放入 ${r.ids.map(x=>ING[x].name).join('、')}。注意每拍只有一次换位。`);else notify('食材不足，无法下锅。');return}
if(act.startsWith('flame:')){const n=Number(act.slice(6));notify(setFlame(game,n)?'火力已改变。黄色预测表示理想区间，红色提示焦糊风险。':'无法调整火力。');return}
if(act==='toss'){notify(tossWok(game)?'颠锅完成！外圈食材已转位，看看下一拍的熟度预测。':'本拍换位机会已用完。');return}
if(act.startsWith('breakprep:')){notify(breakPrep(game,act.slice(10))?'波次间应急备餐成功，原料已真实消耗。':'本波已用过机会或原料不足。');return}
if(act.startsWith('prep:')){notify(prepDish(game,act.slice(5))?'已预制一份，材料已从仓库扣除。':'缺少原料，备餐失败。');return}
if(act==='service-toggle'){notify(setServicePaused(game,!game.service.paused)?game.service.paused?'已暂停营业：模拟时间停止。':'已开始营业：时间和顾客耐心将正常推进。':'当前不能操作暂停。');return}
if(act==='resume-break'){notify(resumeBreak(game)?'下一波开始，注意进门顾客和两个工位的产能。':'无法继续营业。');return}
if(act==='clear-selection'){selectedStation=null;selectedOrderId=null;render();return}
if(act.startsWith('prior:')){notify(expedite(game,act.slice(6))?'已调整同工位的优先排队顺序。':'该订单无法调整。');return}
if(act.startsWith('manual:')){notify(markManual(game,act.slice(7))?'手动烹饪：营业时间暂停，出锅后仍占工位标准制作秒数。':'食材不足或无法手动操作。');return}
switch(act){case'to-field':nextPhase(game,'field');message='选一个食材，再决定采集路线。';break;case'skip-field':skipField(game);message='已跳过探索，直接进入研发。';break;case'collect':{const r=collectNode(game);message=r.message;break;}case'skip-node':{const r=collectNode(game,'skip');message=r.message;break;}case'retreat':settleField(game);message='探索奖励已真实入库，去炒锅试试新食材！';break;case'heat':beat(game);message=`第 ${game.cook?.beats||0} 拍热量已结算，观察颜色和热量区间。`;break;case'finish-cook':{const r=finishCook(game);message=r?.sellable?`已解锁或改良「${RECIPES[r.recipeId].name}」，品质 ${r.quality}！`:`料理未达标：${r?.reason||'未知'}，材料已消耗。`;break;}case'to-menu':nextPhase(game,'menu');message='组合三道菜，留意炒锅与炖锅的产能。';break;case'to-prep':if(canMenu(game)){nextPhase(game,'prep');message='菜单已锁定。可以少量提前备餐。'}break;case'open':nextPhase(game,'service');createService(game);selectedOrderId=null;selectedStation=null;message='餐厅场景已经准备好。点击「开始迎客」，再点桌子处理真实客单。';break;case'close':closeService(game);message='订单日志生成日报，检查产能瓶颈和顾客口味。';break;case'to-upgrade':nextPhase(game,'upgrade');message='可以进行永久升级，再开始下一天。';break;case'upgrade':notify(buyUpgrade(game)?'已升级炒锅：今后每份炒菜 -2 秒。':'金币不足，升级失败。');return;case'next-day':advanceDay(game);message='新的一天开始，库存与菜谱都保留下来了。';break;}render()}
app.addEventListener('click',e=>{const tile=e.target.closest('[data-tile]');if(tile){const i=Number(tile.dataset.tile);if(!game.cook)return;if(tileSelected===null){if(!game.cook.tiles[i])return;tileSelected=i;message='再点击目标格（空格移动，有食材交换）。';render()}else{const from=tileSelected;tileSelected=null;message=moveTile(game,from,i)?'已调整锅中食材位置。':'本拍换位机会已经用完。';render()}return}const b=e.target.closest('[data-act]');if(b){if(b.disabled)return;action(b.dataset.act);return}const seat=e.target.closest('[data-scene-seat]');if(seat){const num=Number(seat.dataset.sceneSeat);const o=game.service?.orders.find(x=>x.tableId===num&&['queued','cooking'].includes(x.status));selectedOrderId=o?.id||null;selectedStation=null;notify(o?`已选中 ${CUSTOMERS[o.segment]?.name||'顾客'}，检查等待状态。`:`${num+1} 号桌空闲，点击工位可查看后厨任务。`);return}const st=e.target.closest('[data-scene-station]');if(st){selectedStation=st.dataset.sceneStation;selectedOrderId=null;notify(`已查看 ${selectedStation==='WOK'?'炒锅':'炖锅'} 的生产与排单。`);return}const select=e.target.closest('[data-select-order]');if(select){selectedOrderId=select.dataset.selectOrder;selectedStation=null;render();return}const target=e.target.closest('[data-target]');if(target){game.selectedTarget=target.dataset.target;render();return}const route=e.target.closest('[data-route]');if(route){enterField(game,route.dataset.route);notify('已进入路线。完成节点后可随时撤离。');return}const buy=e.target.closest('[data-buy]');if(buy){notify(purchase(game,buy.dataset.buy)?'采购成功：金币减少，材料入库。':'金币不足。');return}});
app.addEventListener('change',e=>{if(e.target.matches('[data-slot]')){const idx=Number(e.target.dataset.slot);game.menu[idx]=e.target.value;notify('已调整菜单，观察套餐共鸣与工位负载。')}});
// iOS Safari: support touch movement in addition to the more reliable two-tap path.
app.addEventListener('pointerdown',e=>{const t=e.target.closest('[data-tile]');if(t&&game.cook&&game.cook.tiles[Number(t.dataset.tile)])dragFrom={from:Number(t.dataset.tile),x:e.clientX,y:e.clientY}}, {passive:true});
app.addEventListener('pointerup',e=>{if(!dragFrom)return;const d=dragFrom;dragFrom=null;if(Math.hypot(e.clientX-d.x,e.clientY-d.y)<20)return;const dest=document.elementFromPoint(e.clientX,e.clientY)?.closest('[data-tile]');if(dest){tileSelected=null;message=moveTile(game,d.from,Number(dest.dataset.tile))?'拖拽换位成功。':'本拍只能移动一次。';render()}},{passive:true});
setInterval(()=>{if(document.hidden)return;if(game.phase==='service'&&game.service&&!game.cook&&!game.service.done&&!game.service.paused&&!game.service.breakAt){tick(game,1);if(game.service.done)message='营业结束：点击下方按钮查看日报。';else if(game.service.breakAt)message='波次休整！你可以应急备菜，或直接迎接下一波。';render()}},750);
document.addEventListener('visibilitychange',()=>{if(document.hidden&&game.phase==='service'&&game.service&&!game.service.paused&&!game.service.done&&!game.service.breakAt){game.service.paused=true;message='已切到后台：营业自动暂停，返回后可继续。';save(game)}});
render();