import {ING,RECIPES,FORECAST,ROUTES} from './data.js';
import {PHASES,newGame,save,load,today,enterField,collectNode,settleField,skipField,purchase,startCook,moveTile,beat,finishCook,synergyFor,canMenu,prepDish,createService,tick,expedite,markManual,closeService,nextPhase,advanceDay,buyUpgrade,canUse} from './engine.js';
let game=load()||newGame();let message='欢迎来到怪味食堂！先观察今晚的客人。';let tileSelected=null;let dragFrom=null;const app=document.querySelector('#app');
const clean=s=>String(s).replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;').replaceAll('"','&quot;');
const btn=(action,label,disabled=false,cls='')=>`<button class="button ${cls}" data-act="${action}" ${disabled?'disabled':''}>${label}</button>`;
const ingredients=()=>Object.entries(ING).map(([id,ing])=>`<span class="stock">${ing.emoji} ${ing.name} <b>×${game.inventory[id]||0}</b></span>`).join('');
function header(){const phase={forecast:'今日情报',field:'野外取材',research:'研发料理',menu:'三菜构筑',prep:'备餐选择',service:'营业中',report:'今晚日报',upgrade:'成长与新日'}[game.phase];return `<header><div><div class="eyebrow">WEIRD TASTE DINER · 核心玩法验证</div><h1>🍳 怪味食堂 <span class="subver">v0.1</span></h1></div><div class="daybadge">第 ${game.cycle} 轮<br><strong>DAY ${game.day}</strong></div></header><div class="stats"><span>🪙 ${game.coins} 金币</span><span>⭐ ${game.reputation} 声望</span><span>📖 ${Object.keys(game.recipes).length}/5 道菜</span></div><nav class="steps">${['情报','取材','研发','菜单','备餐','营业','日报','升级'].map((n,i)=>`<span class="${PHASES[i]===game.phase?'current':''} ${i<PHASES.indexOf(game.phase)?'completed':''}">${n}</span>`).join('')}</nav><p class="toast" role="status">${clean(message)}</p><section class="panel inventory"><div class="paneltop"><h2>🍱 食材仓库</h2><small>真实库存 · 跨日保留</small></div><div class="stockrow">${ingredients()}</div></section><div class="phaseheading"><h2>${phase}</h2><small>${today(game).name}</small></div>`}
function forecast(){const t=today(game);const guide=game.day===1?'建议尝试蘑菇焖鸡 + 菌香小炒，形成「菌香组合」。':game.day===2?'冒险者喜欢辣味。去取火椒，研发辣椒炒肉，再调整菜单。':'今晚踢馆！上架辣椒炒肉，与蘑菇焖鸡形成「辛香暖胃」，评委看品质与出餐。';return `<section class="panel feature"><div class="eyebrow">TODAY'S FORECAST</div><h2>${t.name}</h2><p>${t.hint}</p><div class="tip">💡 ${guide}</div>${game.day===3?'<div class="dangerhint">🔥 爆炎厨王：辛香与猛火 / 对手 70 分 / 最后一单为评委单。首胜解锁「猛火掌控」。</div>':''}${btn('to-field','查看食材路线 →',false,'primary')}</section>`}
function field(){let f=game.field;return `<section class="panel"><p>缺什么，就找什么。采集所得会直接进入餐馆仓库（每个游戏日最多一次）。</p>${!f?`<h3>① 指定目标食材</h3><div class="choices">${Object.entries(ING).map(([id,ing])=>`<button data-target="${id}" class="chip ${game.selectedTarget===id?'selected':''}">${ing.emoji} ${ing.name}</button>`).join('')}</div><h3>② 选择路线</h3><div class="routegrid">${ROUTES.map(x=>`<button class="route" data-route="${x.id}"><strong>${x.emoji} ${x.name}</strong><small>${x.subtitle}</small><span>目标保底：${ING[game.selectedTarget].name} ×2</span></button>`).join('')}</div>${btn('skip-field','库存足够，跳过探索 →')}`:`<div class="fieldhead"><strong>${f.route==='safe'?'🌿 安全采集线':'🦬 野牛狩猎线'}</strong><span>❤️ ${'♥'.repeat(f.hp)} · 🎒 ${Object.keys(f.bag).length}/6 格</span></div><div class="bag">${Object.entries(f.bag).length?Object.entries(f.bag).map(([id,n])=>`${ING[id].emoji} ${ING[id].name} ×${n}`).join('　'):'背包为空'}</div>${f.node<f.sequence.length&&!f.finished?`<div class="node"><div class="eyebrow">节点 ${f.node+1}/3</div><h2>${f.sequence[f.node].type==='danger'?'⚠️':f.sequence[f.node].type==='event'?'✨':'🌱'} ${f.sequence[f.node].label}</h2><p>可获得 ${ING[f.sequence[f.node].id].name} ×${f.sequence[f.node].n} ${f.sequence[f.node].type==='danger'?'· 有损伤风险':''}</p>${btn('collect','采集 / 应对 →',false,'primary')}${btn('skip-node','绕过此节点')}</div>`:`<div class="tip">探索节点已完成，可以结算背包。</div>`}${btn('retreat','带上已采集食材回店 →',false,'strong')}`}</section>`}
const cookNames=Object.entries(RECIPES);
const choicesCook=()=>`<section class="panel"><h3>从已知配方开始</h3><div class="recipes">${cookNames.filter(([id,r])=>!r.hidden||game.recipes[id]).map(([id,r])=>`<div class="reciperow"><span class="recipeicon">${r.emoji}</span><div class="recipedesc"><b>${r.name}${game.recipes[id]?' · 已会':' · 待研发'}</b><small>${r.ids.map(x=>ING[x].emoji).join(' + ')} · ${r.method==='stir'?'爆炒':'焖煮'} ${r.station} · ${r.time}s</small></div>${btn(`try:${id}`,'下锅',!canUse(game,r.ids))}</div>`).join('')}</div><h3>自由实验 · 寻找隐藏变体</h3><div class="tip">🔥 线索：让火椒与肉相邻至少两拍，再让蒜瓣在中心旺火爆香。</div><div class="freecook">${[0,1,2].map((i)=>`<select aria-label="自选食材${i+1}" data-exp-ing="${i}"><option value="">${i===2?'（可选）第三食材':'选择食材'}</option>${Object.entries(ING).map(([id,ing])=>`<option value="${id}" ${(i===0&&id==='chicken'||i===1&&id==='mushroom')?'selected':''}>${ing.emoji} ${ing.name}</option>`).join('')}</select>`).join('')}<select aria-label="选择技法" id="exp-method"><option value="stir">🔥 爆炒</option><option value="stew">🍲 焖煮</option></select></div>${btn('free-cook','🧪 自由下锅尝试',false,'strong')}<p class="hint">重复食材或库存不足时无法开始实验，实验失败仍真实耗材。</p>${btn('to-menu','暂时不做，去搭配菜单 →',false,'primary')}</section><section class="panel"><h3>快速采购（防止缺料卡住）</h3><div class="choices">${['chicken','chili','garlic','mushroom','cabbage'].map(id=>`<button class="chip" data-buy="${id}">+1 ${ING[id].emoji} <small>🪙${ING[id].cost}</small></button>`).join('')}</div></section>`;
function cookPanel(){const c=game.cook;if(!c)return '';const temp=c.method==='stir'?[1,2,1,2,3,2,1,2,1]:[1,1,1,1,2,1,1,1,1];const tiles=c.tiles.map((t,i)=>`<button class="tile ${t?'filled':''} ${tileSelected===i?'active':''}" data-tile="${i}"><span class="heatnote">+${temp[i]}🔥</span>${t?`<span class="foodicon">${ING[t.id].emoji}</span><small>${ING[t.id].name}</small><b>热量 ${t.heat}</b>`:'<span class="emptytile">＋</span>'}</button>`).join('');return `<section class="panel cookpanel"><div class="paneltop"><h2>🍳 ${c.method==='stir'?'爆炒':'焖煮'}构筑盘</h2><span class="badge">${c.beats}/3 拍</span></div><p class="hint">点击食材，再点另一格换位；也可拖动。首拍可自由摆放，此后每拍限换位 1 次。中心火最旺。</p><div class="wok"><div class="board">${tiles}</div></div><div class="heatguide">${c.tiles.filter(Boolean).map(t=>`<span class="${t.heat>ING[t.id].hi?'over':t.heat>=ING[t.id].lo?'ripe':''}">${ING[t.id].emoji} ${t.heat} / ${ING[t.id].lo}–${ING[t.id].hi}</span>`).join('')}</div><div class="beats">${[1,2,3].map(n=>`<span class="${c.beats>=n?'on':''}">${c.beats>=n?'●':'○'}</span>`).join('')}</div>${c.beats<3?btn('heat','🔥 确认加热这一拍',false,'primary'):btn('finish-cook','✨ 出锅并评价',false,'primary')}<p class="hint">${[...new Set(c.effects)].join(' · ')||'试试让火椒与肉相邻两拍，或让蒜瓣在中心爆香。'}</p></section>`}
function cookResult(){const r=game.lastCook;if(!r)return '';return `<section class="panel result"><h3>${r.sellable?'🎉 成功研发！':'🧪 这锅未达标'}</h3><div class="bigscore">${r.quality}<small>/100 品质</small></div><h3>${r.recipeId?RECIPES[r.recipeId].name:'未知组合'}</h3><p>${r.reason} ${r.effects.join(' · ')}</p><div class="heatguide">${r.heat.map(t=>`<span>${ING[t.id].emoji} ${t.heat}/${t.ideal}</span>`).join('')}</div></section>`}
function research(){return `${game.cook?cookPanel():`${cookResult()}${choicesCook()}`}`}
function menu(){let sy=synergyFor(game.menu);const count={};game.menu.forEach(id=>{const st=RECIPES[id]?.station;if(st)count[st]=(count[st]||0)+1});const ids=Object.keys(game.recipes);return `<section class="panel"><p>从已研发料理中选择 3 道。比较风味覆盖、厨具占用与套餐共鸣。</p>${[0,1,2].map(i=>`<div class="slot"><span>菜单 ${i+1}</span><select data-slot="${i}">${ids.map(id=>`<option value="${id}" ${game.menu[i]===id?'selected':''}>${RECIPES[id].emoji} ${RECIPES[id].name} · ${RECIPES[id].station}</option>`).join('')}</select></div>`).join('')}<div class="synergy"><strong>${sy?'✨ 已激活 '+sy:'暂无主共鸣'}</strong><p>${sy==='辛香暖胃'?'冒险者对辣味菜的适配增加。':sy==='菌香组合'?'家庭与评论家的菌香适配增加。':'尝试辣味肉菜 + 炖煮菜，或两道不同菌香菜。'}</p></div><div class="kitchenpreview"><div>🍳 WOK 炒锅<br><b>${count.WOK||0} 道菜争抢</b></div><div>🍲 POT 炖锅<br><b>${count.POT||0} 道菜争抢</b></div></div>${btn('to-prep','确认今晚菜单 →',!canMenu(game),'primary')}</section><section class="panel"><h3>成本 / 产能参考</h3>${game.menu.map(id=>RECIPES[id]?`<div class="economyline">${RECIPES[id].emoji} ${RECIPES[id].name}<span>🪙${RECIPES[id].price} · ${RECIPES[id].time}s · ${RECIPES[id].station}</span></div>`:'').join('')}</section>`}
function prep(){return `<section class="panel"><p>可提前制作少量菜。备餐立即消耗真实食材，省去营业时的排队；未卖完会报损。</p><div class="tip">${game.day===3?'🔥 挑战营业：评委喜欢辣味和爆香。':''}本晚共三波、约 7 单、两张餐桌、WOK/POT 各一台。</div>${game.menu.map(id=>{const r=RECIPES[id];return `<div class="reciperow"><span class="recipeicon">${r.emoji}</span><div class="recipedesc"><b>${r.name}</b><small>已备 ${game.prep[id]||0} 份 · ${r.station} ${r.time}s</small></div>${btn(`prep:${id}`,'+1份',!canUse(game,r.ids))}</div>`}).join('')}${btn('open','🛎️ 开始今晚营业',false,'primary')}</section>`}
function service(){if(game.cook)return `<section class="panel"><div class="tip">营业时间已暂停。出锅后将支付标准工位制作时间。</div></section>${cookPanel()}`;const v=game.service;if(!v)return '';const isDone=v.done;const served=v.orders.filter(o=>o.status==='served').length;const waiting=v.orders.filter(o=>o.status==='queued'||o.status==='cooking');const arrive=v.orders.filter(o=>o.status==='waiting');return `<section class="panel"><div class="servicehead"><div><strong>第 ${v.wave+1}/3 波 · ${game.day===3?'🔥 厨王挑战':'正常营业'}</strong><small>模拟时间 ${v.time}s · 已出 ${served}/${v.orders.length} 单</small></div><span class="badge">🪙 +${v.income}</span></div><div class="stationgrid">${['WOK','POT'].map(st=>`<div class="station ${v.stations[st]?'busy':''}"><b>${st==='WOK'?'🍳 WOK':'🍲 POT'}</b><small>${v.stations[st]?`制作中 · 剩余 ${v.stations[st].left}s`:'空闲'}</small></div>`).join('')}</div><div class="orderlist">${v.orders.filter(o=>o.status!=='waiting').map(o=>{const r=RECIPES[o.recipeId],pct=Math.max(0,Math.round((1-(v.time-o.arrival)/o.patience)*100));return `<div class="order ${o.status} ${o.segment==='critic'?'vip':''}"><div class="orderbody"><b>${o.segment==='critic'?'⭐ 评委 ':''}${r?.emoji||''} ${r?.name||'无菜'} <span>· ${o.status==='served'?'✅ 已出':o.status==='left'?'❌ 离店':o.status==='rejected'?'⛔ 拒单':o.status==='cooking'?'🔥 烹饪中':'🧾 排队'}</span></b><small>${o.segment==='adventurer'?'⚔️ 冒险者':o.segment==='family'?'👨‍👩‍👧 家庭':o.segment==='regular'?'🙂 普通':'⭐ 评论家'} · 匹配 ${o.fit} ${o.sat!=null?' · 评价 '+o.sat:''}</small>${['queued','cooking'].includes(o.status)?`<div class="patience"><span style="width:${pct}%"></span></div>`:''}</div>${o.status==='queued'?`<div class="orderactions">${btn(`prior:${o.id}`,'优先',false,'tiny')}${btn(`manual:${o.id}`,'手做',v.manualUsed>=2||!!o.manual||!!game.cook,'tiny secondary')}</div>`:''}</div>`}).join('')}</div><div class="tip">${isDone?'今晚营业结束，查看实际订单日志与经营反馈。':'普通订单自动制作。点「优先」改变同工位的队列，重要订单可手动做饭。'}</div>${isDone?btn('close','查看营业日报 →',false,'primary'):''}</section>`}
function report(){const r=game.report;if(!r)return '';return `<section class="panel report"><div class="eyebrow">NIGHT REPORT · DAY ${r.day}</div><div class="metrics"><div><small>销售收入</small><strong>🪙 ${r.revenue}</strong></div><div><small>原料耗用估值</small><strong>${r.cost}</strong></div><div><small>经营贡献利润</small><strong>${r.profit}</strong></div><div><small>顾客满意度</small><strong>${r.sat}</strong></div><div><small>成功交付</small><strong>${r.served}/7</strong></div><div><small>离店 / 拒单</small><strong>${r.left} / ${r.rejected}</strong></div></div><div class="tip">💡 ${r.suggested}</div><h3>📊 菜品销量</h3>${Object.entries(r.byDish).map(([id,d])=>`<div class="economyline">${RECIPES[id].name}<span>${d.count} 份 · 评价 ${Math.round(d.totalSat/d.count)}</span></div>`).join('')||'<p>本晚没有售出菜品。</p>'}<p class="hint">锅具忙碌：WOK ${r.congestion.WOK}s / POT ${r.congestion.POT}s；主共鸣：${r.synergy||'无'}。</p>${r.challenge?`<div class="challenge"><h2>${r.won?'🏆 击败爆炎厨王！':'🔥 厨王挑战未通过'}</h2><div class="bigscore">${r.challenge.score}<small> / 70 目标</small></div><div class="metrics fours">${[['顾客体验',r.challenge.service],['主题掌握',r.challenge.theme],['履约率',r.challenge.fulfillment],['评委料理',r.challenge.signature]].map(([n,v])=>`<div><small>${n}</small><strong>${v}</strong></div>`).join('')}</div><p>${r.won?'永久解锁「猛火掌控」：爆炒时可修正一次过火热量。':'失败不清空仓库与收益，下轮第三天可以重试。'}</p></div>`:''}${btn('to-upgrade','结束本日，查看成长 →',false,'primary')}</section>`}
function upgrade(){return `<section class="panel"><h2>🍽️ 食堂持续成长</h2><p>永久保留菜谱、金币、原材料与厨王技法。完成三天后开启新一轮经营主题。</p><div class="tip">${game.tech?'🔥 猛火掌控已解锁：每锅爆炒可对一份过火食材修正 -1 热量。':'🔒 猛火掌控：首次战胜爆炎厨王后获得。'}</div><div class="reciperow"><span class="recipeicon">⚙️</span><div class="recipedesc"><b>炒锅节能改装</b><small>永久升级 · WOK 制作时间 -2 秒（60 金币）</small></div>${btn('upgrade','升级',game.upgrade||game.coins<60)}</div>${btn('next-day',game.day===3?'🔁 进入新一轮 →':'🌅 开始下一天 →',false,'primary')}</section>`}
function render(){app.innerHTML=header()+({forecast,field,research,menu,prep,service,report,upgrade}[game.phase])()+`<footer>🧪 无美术占位 · 使用固定规则 / 真实库存与经营结算 <button class="reset" data-act="reset">重置试玩</button></footer>`;save(game)}
function notify(msg){message=msg;render()}
function action(act){if(act==='reset'){if(!confirm('确定清空本机原型存档，从第一天重开？'))return;game=newGame();tileSelected=null;notify('测试存档已重置。');return}
if(act==='free-cook'){const ids=[...app.querySelectorAll('[data-exp-ing]')].map(e=>e.value).filter(Boolean);const method=app.querySelector('#exp-method').value;if(new Set(ids).size!==ids.length){notify('不能在同一锅加入两次相同食材。');return}notify(startCook(game,ids,method)?'自由实验已开始，试试不同温区与联动条件。':'请选择两至三种有库存的食材。');return}
if(act.startsWith('try:')){const id=act.slice(4),r=RECIPES[id];if(startCook(game,r.ids,r.method))notify(`已放入 ${r.ids.map(x=>ING[x].name).join('、')}。注意每拍只有一次换位。`);else notify('食材不足，无法下锅。');return}
if(act.startsWith('prep:')){notify(prepDish(game,act.slice(5))?'已预制一份，材料已从仓库扣除。':'缺少原料，备餐失败。');return}
if(act.startsWith('prior:')){notify(expedite(game,act.slice(6))?'已调整同工位的优先排队顺序。':'该订单无法调整。');return}
if(act.startsWith('manual:')){notify(markManual(game,act.slice(7))?'手动烹饪：营业时间暂停，出锅后仍占工位标准制作秒数。':'食材不足或无法手动操作。');return}
switch(act){case'to-field':nextPhase(game,'field');message='选一个食材，再决定采集路线。';break;case'skip-field':skipField(game);message='已跳过探索，直接进入研发。';break;case'collect':{const r=collectNode(game);message=r.message;break;}case'skip-node':{const r=collectNode(game,'skip');message=r.message;break;}case'retreat':settleField(game);message='探索奖励已真实入库，去炒锅试试新食材！';break;case'heat':beat(game);message=`第 ${game.cook?.beats||0} 拍热量已结算，观察颜色和热量区间。`;break;case'finish-cook':{const r=finishCook(game);message=r?.sellable?`已解锁或改良「${RECIPES[r.recipeId].name}」，品质 ${r.quality}！`:`料理未达标：${r?.reason||'未知'}，材料已消耗。`;break;}case'to-menu':nextPhase(game,'menu');message='组合三道菜，留意炒锅与炖锅的产能。';break;case'to-prep':if(canMenu(game)){nextPhase(game,'prep');message='菜单已锁定。可以少量提前备餐。'}break;case'open':nextPhase(game,'service');createService(game);message='开门营业！订单将随模拟时间进入队列。';break;case'close':closeService(game);message='订单日志生成日报，检查产能瓶颈和顾客口味。';break;case'to-upgrade':nextPhase(game,'upgrade');message='可以进行永久升级，再开始下一天。';break;case'upgrade':notify(buyUpgrade(game)?'已升级炒锅：今后每份炒菜 -2 秒。':'金币不足，升级失败。');return;case'next-day':advanceDay(game);message='新的一天开始，库存与菜谱都保留下来了。';break;}render()}
app.addEventListener('click',e=>{const tile=e.target.closest('[data-tile]');if(tile){const i=Number(tile.dataset.tile);if(!game.cook)return;if(tileSelected===null){if(!game.cook.tiles[i])return;tileSelected=i;message='再点击目标格（空格移动，有食材交换）。';render()}else{const from=tileSelected;tileSelected=null;message=moveTile(game,from,i)?'已调整锅中食材位置。':'本拍换位机会已经用完。';render()}return}const b=e.target.closest('[data-act]');if(b){if(b.disabled)return;action(b.dataset.act);return}const target=e.target.closest('[data-target]');if(target){game.selectedTarget=target.dataset.target;render();return}const route=e.target.closest('[data-route]');if(route){enterField(game,route.dataset.route);notify('已进入路线。完成节点后可随时撤离。');return}const buy=e.target.closest('[data-buy]');if(buy){notify(purchase(game,buy.dataset.buy)?'采购成功：金币减少，材料入库。':'金币不足。');return}});
app.addEventListener('change',e=>{if(e.target.matches('[data-slot]')){const idx=Number(e.target.dataset.slot);game.menu[idx]=e.target.value;notify('已调整菜单，观察套餐共鸣与工位负载。')}});
// iOS Safari: support touch movement in addition to the more reliable two-tap path.
app.addEventListener('pointerdown',e=>{const t=e.target.closest('[data-tile]');if(t&&game.cook&&game.cook.tiles[Number(t.dataset.tile)])dragFrom={from:Number(t.dataset.tile),x:e.clientX,y:e.clientY}}, {passive:true});
app.addEventListener('pointerup',e=>{if(!dragFrom)return;const d=dragFrom;dragFrom=null;if(Math.hypot(e.clientX-d.x,e.clientY-d.y)<20)return;const dest=document.elementFromPoint(e.clientX,e.clientY)?.closest('[data-tile]');if(dest){tileSelected=null;message=moveTile(game,d.from,Number(dest.dataset.tile))?'拖拽换位成功。':'本拍只能移动一次。';render()}},{passive:true});
setInterval(()=>{if(game.phase==='service'&&game.service&&!game.cook&&!game.service.done){tick(game,1);if(game.service.done)message='营业结束：点击下方按钮查看日报。';render()}},650);
render();